export { VeilClient } from "./client";
export { createStrk20RuntimeUnavailableError } from "./client";
export {
  ChannelEncryptionAdapter,
  exportChannelKey,
  generateChannelKey,
  type ChannelEncryptionAdapterConfig,
  type ChannelKeyMaterial,
} from "./channel-encryption";
export { DirectHelperTransport, channelIdToFelt } from "./direct_helper_transport";
export { deriveOpaqueConversationTag } from "./conversation-tag";
export {
  EcdhChannelEncryptionAdapter,
  PrivacyPoolChannelEncryptionAdapter,
  decryptMessage,
  deriveSharedSecret,
  encryptMessage,
  exportEcdhPublicKey,
  generateEcdhKeyPair,
  validateTimelineNonces,
  type DecryptMessageInput,
  type DeriveSharedSecretInput,
  type EcdhChannelEncryptionAdapterConfig,
  type EcdhKeyPair,
  type EcdhPrivateKeyMaterial,
  type EcdhPublicKeyMaterial,
  type EncryptMessageInput,
  type PrivacyPoolChannelEncryptionAdapterConfig,
  type PrivacyPoolSecretMaterial,
} from "./ecdh";
export {
  PRIVACY_POOL_CHANNEL_KEY_TAG,
  PRIVACY_POOL_CHANNEL_MARKER_TAG,
  PRIVACY_POOL_ENC_CHANNEL_KEY_TAG,
  PRIVACY_POOL_ENC_SENDER_ADDR_TAG,
  PRIVACY_POOL_SUBCHANNEL_ID_TAG,
  PRIVACY_POOL_SUBCHANNEL_MARKER_TAG,
  STARK_CURVE_HALF_ORDER,
  STARK_CURVE_ORDER,
  STARK_FIELD_PRIME,
  computeEncChannelKeyMask,
  computeEncSenderAddrMask,
  computePrivacyPoolChannelKey,
  computePrivacyPoolChannelMarker,
  computePrivacyPoolSubchannelId,
  computePrivacyPoolSubchannelMarker,
  decryptChannelInfo,
  deriveMessageKey,
  generatePrivacyScalar,
  derivePrivacyPublicKey,
  deriveReceiverSharedX,
  deriveSenderSharedX,
  encryptChannelInfo,
  generateEphemeralKeyPair,
  type ComputeChannelKeyInput,
  type ComputeChannelMarkerInput,
  type ComputeSubchannelMarkerInput,
  type DecryptedChannelInfo,
  type DecryptChannelInfoInput,
  type DeriveMessageKeyInput,
  type EncChannelInfo,
  type EncryptChannelInfoInput,
  type SenderSharedXResult,
  type StarkEphemeralKeyPair,
} from "./privacy_pool_ecdh";
export {
  BrowserEncryptionIdentityStore,
  MemoryEncryptionIdentityStore,
  VeilEncryptionIdentityService,
  identityError,
  type EncryptionIdentityRecord,
  type EncryptionIdentityStore,
} from "./encryption-identity";
export {
  addRegistrationSafetyMargin,
  EncryptionPublicKeyRegistryService,
  validatePublicKey,
  type ResolvedEncryptionPublicKey,
} from "./encryption-key-registry";
export {
  DirectEcdhEncryptionAdapter,
  canonicalKdfContext,
  type DirectEncryptionPeerContext,
} from "./direct-message-encryption";
export {
  PrivacyPoolChannelBootstrapEncryptionAdapter,
  assertShieldedChannelBootstrapMetadata,
  type PrivacyPoolChannelBootstrapEncryptionAdapterConfig,
  type PrivacyPoolChannelLifecycle,
  type PrivacyPoolChannelBootstrapMaterial,
  type PrivacyPoolChannelRecoveryMaterial,
  type ResolvePrivacyPoolChannelBootstrapInput,
  type ResolvePrivacyPoolChannelRecoveryInput,
} from "./shielded_message_runtime";
export {
  BrowserEncryptedPayloadStore,
  MemoryEncryptedPayloadStore,
  createDefaultEncryptedPayloadStore,
  type EncryptedPayloadEnvelope,
  type EncryptedPayloadStore,
} from "./encrypted-payload-store";
export { MockEncryptionAdapter, hashToFelt } from "./encryption";
export { feltChunksToString, stringToFeltChunks } from "./payload-chunks";
export { VeilSessionError, VeilSessionKeyManager } from "./session-key-manager";
export {
  BrowserSessionKeyStore,
  MemorySessionKeyStore,
  createDefaultSessionKeyStore,
} from "./session-key-store";
export {
  AvnuPrivacyPoolTransport,
  MockPrivacyPoolAdapter,
  RealPrivacyPoolAdapter,
  ResearchPrivacyPoolAdapter,
  StarknetPrivacyPoolTransport,
} from "./privacy_pool_adapter";
export {
  PRIVACY_POOL_ABI_CAPABILITIES,
  PRIVACY_POOL_CLIENT_ACTIONS,
  PRIVACY_POOL_CLIENT_ACTION_PHASES,
  PRIVACY_POOL_CLIENT_FUNCTIONS,
  PRIVACY_POOL_EVENT_ABI,
  PRIVACY_POOL_SERVER_FUNCTIONS,
  PRIVACY_POOL_SOURCE_CONSTRAINTS,
  PRIVACY_POOL_SERVER_ACTIONS,
  PRIVACY_POOL_VIEW_FUNCTIONS,
} from "./privacy_pool_abi";
export {
  PRIVACY_POOL_CLIENT_ACTION_PHASES as PRIVACY_POOL_CANONICAL_CLIENT_ACTION_PHASES,
  PRIVACY_POOL_CLIENT_ACTION_VARIANTS,
  analyzeClientActionBatch,
  assertValidClientActionBatch,
  buildPrivacyPoolChannelActions,
  buildPrivacyPoolMessageActions,
  createEncNoteAction,
  createOpenNoteAction,
  depositAction,
  encodeClientAction,
  encodeClientActions,
  invokeExternalAction,
  openChannelAction,
  openSubchannelAction,
  prepareApplyActionsCall,
  prepareCompileActionsCall,
  prepareCompileActionsCalldata,
  setViewingKeyAction,
  useNoteAction,
  withdrawAction,
  type BuildPrivacyPoolChannelActionsInput,
  type BuildPrivacyPoolMessageActionsInput,
  type PrivacyPoolApplyActionsInput,
  type PrivacyPoolClientAction,
  type PrivacyPoolClientActionBatchAnalysis,
  type PrivacyPoolCompileActionsInput,
  type PrivacyPoolCreateEncNoteActionInput,
  type PrivacyPoolCreateOpenNoteActionInput,
  type PrivacyPoolDepositActionInput,
  type PrivacyPoolInvokeExternalActionInput,
  type PrivacyPoolOpenChannelActionInput,
  type PrivacyPoolOpenSubchannelActionInput,
  type PrivacyPoolSetViewingKeyActionInput,
  type PrivacyPoolUseNoteActionInput,
  type PrivacyPoolWithdrawActionInput,
} from "./privacy_pool_actions";
export {
  PRIVACY_POOL_FEE_MODES,
  PRIVACY_POOL_STRK_FEE_TOKEN_ADDRESS,
  PrivacyPoolFeeError,
  assertPaymasterAccepted,
  estimatePoolFee,
  estimateTotalCost,
  estimateTransactionFee,
  getFeeInfo,
  getSupportedFeeModes,
  type EstimatePoolFeeInput,
  type EstimateTotalCostInput,
  type EstimateTransactionFeeInput,
  type NetworkFeeEstimate,
  type PrivacyPoolFeeErrorCode,
  type PrivacyPoolFeeEstimate,
  type PrivacyPoolFeeInfo,
  type PrivacyPoolFeeMode,
  type PrivacyPoolFeeQuote,
  type PrivacyPoolFeeQuoteProvider,
  type PrivacyPoolFeeTransactionType,
  type PrivacyPoolTotalCostEstimate,
  type StarknetFeeEstimateLike,
  type StarknetFeeEstimatorLike,
} from "./privacy_pool_fees";
export {
  buildStarknetPrivacySdkAction,
} from "./starknet_privacy_sdk";
export {
  VEIL_PRIVACY_ERROR_CODES,
  VeilPrivacyError,
  asPrivacyError,
  privacyErrorMessage,
  type VeilPrivacyErrorCode,
  type VeilPrivacyErrorOptions,
} from "./privacy/errors";
export {
  OFFICIAL_MAX_VIEWING_KEY,
  assertViewingKey,
  createLocalViewingKeyProvider,
} from "./privacy/viewing-key";
export {
  VEIL_OFFICIAL_PRIVACY_SDK_VERSION,
  VEIL_PRIVACY_PROFILE_VERSION,
  createPrivacyNamespace,
  normalizeAddress,
  normalizeAddressBigint,
  readDiscoveryCursor,
  wrapDiscoveryCursor,
  type DiscoveryProviderKind,
  type NamespacedCursor,
  type PrivacyNamespace,
  type PrivacyNamespaceInput,
} from "./privacy/namespace";
export {
  DEFAULT_NOTE_MATURITY_BLOCKS,
  assertSpendableBalance,
  computePrivateBalance,
  isNoteMature,
  type PrivateBalanceSummary,
} from "./privacy/balances";
export {
  DEFAULT_PROVING_REORG_BUFFER,
  computeProvingBlockId,
  serializeProofSubmission,
  submitWithFreshProof,
  type CallAndProofLike,
  type FreshProofResult,
  type FreshProofRetryDependencies,
  type ProofAwareCall,
  type ProofSubmissionDetails,
} from "./privacy/proving";
export {
  VEIL_OFFICIAL_CHAIN_ID,
  VEIL_OFFICIAL_CHAIN_ID_HEX,
  VEIL_OFFICIAL_OUTSIDE_EXECUTION_VERSION,
  VEIL_OFFICIAL_POOL_COMPATIBILITY,
  VEIL_OFFICIAL_TRANSACTION_VERSION,
  assertOfficialPrivacySdkCompatibility,
  assertScreeningCapableDeposit,
  createOfficialPrivacySdkContext,
  mapSetupRequirement,
  type OfficialPrivacySdkCompatibilityConfig,
  type OfficialPrivacySdkConfig,
  type OfficialPrivacySdkContext,
  type RecipientPrivacyRequirement,
} from "./privacy/official-sdk";
export {
  VEIL_CANONICAL_COMMITMENT_DOMAIN,
  VEIL_CANONICAL_ENVELOPE_ALGORITHM,
  VEIL_CANONICAL_ENVELOPE_VERSION,
  VEIL_CANONICAL_MAX_CHUNKS,
  VEIL_CANONICAL_MAX_ENVELOPE_BYTES,
  VEIL_CANONICAL_OPERATION_DOMAINS,
  buildCanonicalHelperPayload,
  validateCanonicalEnvelope,
  type BuildCanonicalHelperPayloadInput,
  type CanonicalHelperPayload,
  type VeilCanonicalKeyDomain,
  type VeilCanonicalOperation,
  type VeilCiphertextEnvelopeV1,
} from "./privacy/canonical-payload";
export {
  VEIL_MESSAGE_LOCATOR_ENTROPY_BITS,
  createMessageLocatorResolver,
  generateMessageLocator,
  normalizeMessageLocator,
  type MessageLocatorResolver,
} from "./privacy/message-locator";
export {
  OfficialPrivacyTransport,
  OfficialPrivacyTransportError,
  VEIL_CANONICAL_HELPER_SELECTOR,
  VEIL_DIRECT_ENCRYPTED_LABEL,
  VEIL_PRIVACY_TRANSPORT_STATUS,
  evaluateOfficialPrivacyTransport,
  type CanonicalApplicationInvoke,
  type OfficialPrivacyTransportConfig,
  type OfficialPrivacyTransportLogEvent,
  type OfficialPrivacyTransportReason,
  type OfficialPrivacyTransportRoute,
  type OfficialPrivacyTransportSnapshot,
  type OfficialPrivacyTransportSubmission,
  type OfficialPrivacyTransportSubmitter,
  type PrepareOfficialPrivacyTransportInput,
  type PreparedOfficialPrivacyTransport,
  type VeilPrivacyTransportStatus,
} from "./privacy/official-transport";
export {
  TransactionProverClient,
  TransactionProverError,
  VEIL_LOCAL_PROOF_STATUS,
  VEIL_PROVER_HEALTH_STATUS,
  VEIL_TRANSACTION_PROVER_IMAGE,
  VEIL_TRANSACTION_PROVER_PIN,
  evaluateTransactionProverCompatibility,
  validateProverEndpoint,
  type ProofBroadcastCandidate,
  type ProverInvokeV3Transaction,
  type ProverL2ToL1Message,
  type TransactionProofRequestInput,
  type TransactionProofResult,
  type TransactionProverBlockId,
  type TransactionProverConfig,
  type TransactionProverHealthSnapshot,
  type TransactionProverLimitConfig,
  type TransactionProverLogEvent,
  type TransactionProverMode,
  type TransactionProverPinConfig,
  type TransactionProverReason,
  type TransactionProverRetryConfig,
  type TransactionProverTimeoutConfig,
  type VeilLocalProofStatus,
  type VeilProverHealthStatus,
} from "./privacy/transaction-prover";
export {
  OfficialPrivacyFlows,
  type ApprovalResult,
  type ExactApprovalAdapter,
  type FundAndPayInput,
  type FundPrivateEscrowCustodyInput,
  type OfficialPrivacyFlowContext,
  type OfficialPrivacyFlowsConfig,
  type PrivateFlowResult,
  type PrivatePaymentMemoInput,
  type PrivateTransferInput,
  type RefundPrivateEscrowCustodyInput,
  type ReleasePrivateEscrowCustodyInput,
  type PrivacyChainProvider,
  type PrivacyTransactionReceipt,
  type PrivacyTransactionStage,
  type ProofAwareSubmitter,
  type ShieldInput,
  type ShieldResult,
  type WithdrawInput,
} from "./privacy/financial-flows";
export {
  VEIL_PRIVATE_ESCROW_DEPOSIT_ACTION,
  VEIL_PRIVATE_ESCROW_REFUND_ACTION,
  VEIL_PRIVATE_ESCROW_REFUND_DOMAIN,
  VEIL_PRIVATE_ESCROW_RELEASE_ACTION,
  VEIL_PRIVATE_ESCROW_RELEASE_DOMAIN,
  buildPrivateEscrowFundingPlan,
  buildPrivateEscrowRefundCalldata,
  buildPrivateEscrowReleaseCalldata,
  computePrivateEscrowRefundCommitment,
  computePrivateEscrowReleaseCommitment,
  normalizePrivateEscrowFelt,
  normalizePrivateEscrowSettlement,
  type NormalizedPrivateEscrowSettlement,
  type PrivateEscrowFundingInput,
  type PrivateEscrowFundingPlan,
  type PrivateEscrowSettlementInput,
} from "./privacy/private-escrow-settlement";
export {
  BrowserEncryptedPrivacyProfileStore,
  generateDeviceStorageKey,
  type BrowserEncryptedPrivacyProfileStoreConfig,
  type EncryptedPrivacyProfileStore,
} from "./privacy/profile-store";
export {
  VEIL_APPLICATION_KEY_DOMAINS,
  decryptApplicationPayload,
  encryptApplicationPayload,
  type DecryptApplicationPayloadInput,
  type EncryptApplicationPayloadInput,
  type VeilApplicationCiphertext,
  type VeilApplicationEncryptionContext,
  type VeilApplicationKeyDomain,
} from "./privacy/application-encryption";
export {
  VEIL_CLAIM_COMMITMENT_DOMAIN,
  VEIL_CLAIM_SECRET_BYTES,
  computeClaimCommitment,
  createPrivateClaimLink,
  generateClaimSecret,
  normalizeClaimSecret,
  publicClaimUrl,
  readClaimSecretFromFragment,
} from "./privacy/claim-link";
export {
  Strk20WalletApiClient,
  VEIL_STRK20_WALLET_API_SOURCE_COMMIT,
  VEIL_STRK20_WALLET_API_VERSION,
  detectStrk20WalletCapabilities,
  strk20DepositAction,
  strk20InvokeAction,
  strk20TransferAction,
  strk20WithdrawAction,
  type StarknetWalletRequestTransport,
  type Strk20PreparedInvoke,
  type Strk20WalletAction,
  type Strk20WalletApiConfig,
  type Strk20WalletBalance,
  type Strk20WalletCapabilities,
} from "./privacy/wallet-api";
export {
  VeilOnchainContracts,
  createVeilDealCommitments,
  createVeilOnchainContracts,
  type VeilDealCommitmentInput,
  type VeilDealCommitments,
  type VeilEscrowTransactionResult,
  type VeilOfferTransactionResult,
  type VeilOnchainContractsConfig,
  type VeilOnchainTransactionResult,
} from "./onchain_contracts";
export {
  decodeChannelEvent,
  decodeInvokeExternalEvent,
  decodeNoteEvent,
  decodePrivacyPoolEvent,
} from "./event_decoder";
export {
  PrivacyPoolTransactionAnalyzer,
  decodeTransactionCalldata,
} from "./transaction_analyzer";
export {
  TIMELINE_PAYLOAD_DOMAIN,
  computeTimelinePayloadHash,
  createOptimisticTimelineItem,
  encodeInvokeCalldata,
  eventTypeToPayloadKind,
  getEventGroup,
  getEventLabel,
  isEscrowEvent,
  isMessageEvent,
  isOfferEvent,
  isPaymentMemoEvent,
  isProofEvent,
  mergeTimelineItems,
  sortTimeline,
  timelineItemsFromDecodedEvents,
  type TimelinePayloadHashInput,
} from "./timeline";
export {
  VeilEventType,
  type AttachProofInput,
  type AvnuPaymasterLike,
  type AvnuPrivacyActionBuilderLike,
  type AvnuPrivacyChannelActionInput,
  type AvnuPrivacyMessageAction,
  type AvnuPrivacyMessageActionInput,
  type AvnuPrivacyPaymasterLike,
  type AvnuPrivacyPoolTransportConfig,
  type CreateChannelInput,
  type CreateChannelResult,
  type DirectHelperTransportConfig,
  type EncryptedPayload,
  type EncryptionAdapter,
  type EncryptionContext,
  type EscrowStatusInput,
  type FeltLike,
  type InvokeExternalInput,
  type OpenSubchannelInput,
  type OpenSubchannelResult,
  type OfferDecisionInput,
  type OfferInput,
  type PrivacyPoolAdapter,
  type PrivacyPoolAdapterActionResult,
  type PrivacyPoolAdapterMode,
  type PrivacyPoolCreateEncryptedNoteInput,
  type PrivacyPoolInvokeExternalCalldataInput,
  type PrivacyPoolOpenChannelInput,
  type PrivacyPoolOpenSubchannelInput,
  type SendMessageInput,
  type SendPaymentMemoInput,
  type ShieldedChannelBootstrapMetadata,
  type StarknetAccountLike,
  type StarknetCallResult,
  type StarknetContractCall,
  type StarknetExecuteResult,
  type StarknetPrivacyActionBuilderLike,
  type StarknetPrivacyChannelActionInput,
  type StarknetPrivacyMessageAction,
  type StarknetPrivacyMessageActionInput,
  type StarknetPrivacyApplyActionsTransactionInput,
  type StarknetPrivacyCompiledActions,
  type StarknetPrivacyProofResult,
  type StarknetPrivacySdkActionKind,
  type StarknetPrivacySdkExecutionInput,
  type StarknetPrivacySdkLike,
  type StarknetPrivacyPoolTransportConfig,
  type StarknetProviderLike,
  type TimelineItem,
  type TimelineQuery,
  type UseVeilMutationOptions,
  type VeilActor,
  type VeilChannelParticipant,
  type VeilClientConfig,
  type VeilEventGroup,
  type VeilMessageMode,
  type VeilMessageStatus,
  type VeilTimelinePayload,
  type VeilTransport,
} from "./types";
export {
  VEIL_SESSION_DURATION_MS,
  VEIL_SESSION_PERMISSIONS,
  type CreateVeilSessionInput,
  type RefreshVeilSessionInput,
  type VeilSession,
  type VeilSessionAuthorization,
  type VeilSessionAuthorizationChallenge,
  type VeilSessionAuthorizationResult,
  type VeilSessionAuthorizer,
  type VeilSessionDuration,
  type VeilSessionErrorCode,
  type VeilSessionErrorDetails,
  type VeilSessionKeyManagerConfig,
  type VeilSessionKeyStore,
  type VeilSessionManagerLike,
  type VeilSessionPermission,
  type VeilSessionPermissionCheck,
  type VeilSessionRecord,
} from "./session-key-types";
export type {
  DecodedEventCategory,
  DecodedEventField,
  DecodedPrivacyPoolEvent,
  DecodeEventOptions,
  RawStarknetEvent,
  StarknetAbi,
  StarknetAbiEntry,
  StarknetAbiMember,
} from "./event_decoder";
export type {
  AnalyzeTransactionInput,
  DecodedActionField,
  DecodedActionSet,
  DecodedCall,
  DecodedHelperInvoke,
  DecodedPrivacyPoolAction,
  PrivacyPoolTransactionAnalysis,
  PrivacyPoolTransactionAnalyzerConfig,
  RawStarknetReceipt,
  RawStarknetTransaction,
} from "./transaction_analyzer";
