pub const MAX_PAYLOAD_CHUNKS: u64 = 64;
pub const TIMELINE_PAYLOAD_DOMAIN: felt252 = 'VEIL_TIMELINE_V1';
pub const OFFER_COMMITMENT_DOMAIN: felt252 = 'VEIL_OFFER_V1';
pub const ESCROW_COMMITMENT_DOMAIN: felt252 = 'VEIL_ESCROW_V1';
pub const SETTLEMENT_COMMITMENT_DOMAIN: felt252 = 'VEIL_SETTLE_V1';
