import { listStorageKeys, removeStorageKeys } from "../services/storage-service.js";
import { deterministicHex } from "../utils/hash.js";

export function buildRuntimeApi({
  registry,
  connectWallet,
  refreshWalletAssets,
  verifyHelperDeployment,
  submitService,
  mountPrivy,
  dom,
  store,
  logger,
}) {
  return {
    connectWallet,
    refreshWalletAssets,
    verifyHelperDeployment,
    safeSubmit: submitService.safeSubmit,
    mountPrivy,
    beginWalletModal: (...args) => registry.transactionModalController.beginWalletModal(...args),
    updateWalletModalStage: (...args) => registry.transactionModalController.updateWalletModalStage(...args),
    finishWalletModal: (...args) => registry.transactionModalController.finishWalletModal(...args),
    failWalletModal: (...args) => registry.transactionModalController.failWalletModal(...args),
    updateTransactionModalStage: (...args) => registry.transactionModalController.updateTransactionModalStage(...args),
    closeTransactionModal: (...args) => registry.transactionModalController.closeTransactionModal(...args),
    setAppLoading: (...args) => registry.loadingController.setAppLoading(...args),
    clearAppLoading: (...args) => registry.loadingController.clearAppLoading(...args),
    renderLoadingState: (...args) => registry.loadingController.renderLoadingState(...args),
    renderConversationList: (...args) => registry.dealRoomController.renderConversationList(...args),
    renderNewDeal: (...args) => registry.inviteController.renderNewDeal(...args),
    renderChannel: (...args) => registry.dealRoomController.renderChannel(...args),
    renderWorkflowProgress: (...args) => registry.dealRoomController.renderWorkflowProgress(...args),
    openChannel: (...args) => registry.dealRoomController.openChannel(...args),
    renderDeal: (...args) => registry.offerController.renderDeal(...args),
    renderEscrow: (...args) => registry.escrowController.renderEscrow(...args),
    renderPayment: (...args) => registry.paymentController.renderPayment(...args),
    renderWallet: (...args) => registry.walletController.renderWallet(...args),
    renderWalletAssets: (...args) => registry.walletController.renderWalletAssets(...args),
    renderWalletRewards: (...args) => registry.walletController.renderWalletRewards(...args),
    renderSettings: (...args) => registry.walletController.renderSettings(...args),
    renderSettlement: (...args) => registry.settlementController.renderSettlement(...args),
    renderProof: (...args) => registry.settlementController.renderProof(...args),
    currentDealOfferAmount: (...args) => registry.offerController.currentDealOfferAmount(...args),
    awardReward: (...args) => registry.rewardsController.awardReward(...args),
    addLocalItem: (...args) => registry.chatController.addLocalItem(...args),
    updateLocalItem: (...args) => registry.chatController.updateLocalItem(...args),
    sendChat: (...args) => registry.chatController.sendChat(...args),
    sendAttachment: (...args) => registry.chatController.sendAttachment(...args),
    resizeComposerInput: (...args) => registry.chatController.resizeComposerInput(...args),
    applyAiDraft: (...args) => registry.chatController.applyAiDraft(...args),
    openCounterOfferForm: (...args) => registry.offerController.openCounterOfferForm(...args),
    cancelOfferForm: (...args) => registry.offerController.cancelOfferForm(...args),
    createOffer: (...args) => registry.offerController.createOffer(...args),
    counterOffer: (...args) => registry.offerController.counterOffer(...args),
    acceptOffer: (...args) => registry.offerController.acceptOffer(...args),
    showOfferReview: (...args) => registry.offerController.showOfferReview(...args),
    hideOfferReview: (...args) => registry.offerController.hideOfferReview(...args),
    showPaymentReview: (...args) => registry.paymentController.showPaymentReview(...args),
    hidePaymentReview: (...args) => registry.paymentController.hidePaymentReview(...args),
    sendPayment: (...args) => registry.paymentController.sendPayment(...args),
    showEscrowReview: (...args) => registry.escrowController.showEscrowReview(...args),
    hideEscrowReview: (...args) => registry.escrowController.hideEscrowReview(...args),
    submitEscrowDeposit: (...args) => registry.escrowController.submitEscrowDeposit(...args),
    approveEscrowRelease: (...args) => registry.escrowController.approveEscrowRelease(...args),
    releaseEscrow: (...args) => registry.escrowController.releaseEscrow(...args),
    cancelEscrow: (...args) => registry.escrowController.cancelEscrow(...args),
    continueCompletedChannel: (...args) => registry.escrowController.continueCompletedChannel(...args),
    startNewEscrowInCurrentChannel: (...args) => registry.escrowController.startNewEscrowInCurrentChannel(...args),
    closeCurrentDeal: (...args) => registry.escrowController.closeCurrentDeal(...args),
    copyWalletAddress: (...args) => registry.walletController.copyWalletAddress(...args),
    resetWalletConnection: (...args) => registry.walletController.resetWalletConnection(...args),
    requireConnectedWallet: (...args) => registry.walletController.requireConnectedWallet(...args),
    refreshWalletConnection: (...args) => registry.walletController.refreshWalletConnection(...args),
    logoutWallet: (...args) => registry.walletController.logoutWallet(...args),
    clearLocalVeilCache: (...args) => registry.walletController.clearLocalVeilCache(...args),
    copyInviteLink: (...args) => registry.inviteController.copyInviteLink(...args),
    shareInvite: (...args) => registry.inviteController.shareInvite(...args),
    createDealChannel: (...args) => registry.inviteController.createDealChannel(...args),
    acceptPendingCounterparty: (...args) => registry.inviteController.acceptPendingCounterparty(...args),
    declinePendingCounterparty: (...args) => registry.inviteController.declinePendingCounterparty(...args),
    iconRefresh: () => {
      if (window.lucide) window.lucide.createIcons();
      registry.loadingController.renderLoadingState();
    },
    deterministicHex,
    listStorageKeys,
    removeStorageKeys,
    state: store.state,
    dom,
    logger,
  };
}
