import {
  ApiError,
  assertHexHash,
  authenticatePrivyRequest,
  createPrivyClient,
  createRequestContext,
  getServerManagedStarknetWallet,
  hashForLog,
  logEvent,
  requirePost,
  sendError,
} from "../_lib/privy.js";

export default async function handler(request, response) {
  const context = createRequestContext(request, "/api/wallet/sign");

  try {
    logEvent("info", "wallet.sign.request.received", context, {
      method: request.method,
      contentType: request.headers["content-type"],
      authorizationPresent: Boolean(request.headers.authorization || request.headers.Authorization),
    });
    requirePost(request, response, context);

    const { walletId, hash } = request.body || {};
    logEvent("info", "wallet.sign.input.validating", context, {
      walletIdPresent: Boolean(walletId),
      hashPresent: Boolean(hash),
    });
    if (!walletId || !hash) {
      throw new ApiError(
        400,
        "WALLET_SIGN_INPUT_MISSING",
        context.route,
        "walletId and hash are required.",
        "Send the Privy Starknet wallet id and the Starknet hash generated by starknet.js.",
      );
    }
    const normalizedHash = assertHexHash(hash, context);
    const auth = await authenticatePrivyRequest(request, context);
    const client = createPrivyClient(context);
    logEvent("info", "wallet.sign.wallet.lookup.start", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
    });
    const wallet = await getServerManagedStarknetWallet(client, auth.userId, walletId, context);
    if (!wallet) {
      throw new ApiError(
        403,
        "WALLET_MAPPING_MISMATCH",
        context.route,
        "The requested server-managed Starknet wallet is not mapped to the authenticated Privy user.",
        "Fetch the wallet through /api/wallet/starknet after login and sign only with the returned wallet.id.",
        { walletId, userIdHash: hashForLog(auth.userId) },
      );
    }
    logEvent("info", "wallet.sign.wallet.lookup.hit", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
      address: wallet.address,
    });

    logEvent("info", "wallet.sign.start", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
      hashPrefix: `${normalizedHash.slice(0, 10)}...`,
    });
    logEvent("info", "wallet.sign.raw_sign.start", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
      hashPrefix: `${normalizedHash.slice(0, 10)}...`,
    });
    const result = await client.wallets().rawSign(walletId, {
      params: { hash: normalizedHash },
    });
    const signature = typeof result === "string"
      ? result
      : result.signature || result.rawSignature || result.raw_signature || result;

    logEvent("info", "wallet.sign.raw_sign.success", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
      signaturePresent: Boolean(signature),
    });
    logEvent("info", "wallet.sign.success", context, {
      userIdHash: hashForLog(auth.userId),
      walletMode: "server-managed",
      walletId,
      signaturePresent: Boolean(signature),
    });
    response.status(200).json({ signature });
  } catch (error) {
    sendError(response, context, error);
  }
}
